"""Regenerate the decoder golden master from tests/fixtures/packets.txt.

    python3 tools/regen_golden.py

This records what WU_decodeData does *today*, correct or not. It is a characterisation tool,
not a specification: the expected values come from running the code, so running it always
makes the tests pass. That is exactly why it lives in tools/ and not in the test suite.

**Only run this when you have deliberately changed decoder behaviour**, and then read the diff
line by line before committing it. An unexplained diff here means a refactor changed the
numbers this station publishes to Weather Underground, and there is no specification to check
them against -- the formulas were tuned empirically against this hardware.
"""

import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

import WU_decodeData as decode

PACKETS = os.path.join(REPO_ROOT, "tests", "fixtures", "packets.txt")
GOLDEN = os.path.join(REPO_ROOT, "tests", "fixtures", "decode_expected.tsv")

# Called by decodeRawData() for every packet regardless of type.
UNIVERSAL = ("crc16_ccitt", "stationID", "windSpeed", "windDirection")

# Called only for the matching high nibble of byte 0.
BY_TYPE = {
    0x2: "capVoltage",
    0x4: "uvIndex",
    0x5: "rainRate",
    0x6: "solarRadiation",
    0x8: "temperature",
    0x9: "windGusts",
    0xA: "humidity",
    0xE: "rainCounter",
}

# Deliberately NOT frozen: rainRate2, rainInch and batteryStatus are unreferenced dead code
# scheduled for deletion (AUDIT_PLAN items 10 and 24). Freezing them would create friction
# against a removal that is already agreed.

COLUMNS = ["packet"] + list(UNIVERSAL) + ["typed"]


def load_packets(path=PACKETS):
    packets = []
    with open(path) as handle:
        for line in handle:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            packets.append([int(b, 16) for b in line.split()])
    return packets


def render(value):
    """Exact, stable text for a decoder return value."""
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, float):
        return repr(value)
    return str(value)


def decode_row(packet):
    row = [" ".join("%02x" % b for b in packet)]
    for name in UNIVERSAL:
        row.append(render(getattr(decode, name)(packet)))

    typed = BY_TYPE.get(packet[0] >> 4)
    if typed is None:
        row.append("-")
    else:
        row.append("%s=%s" % (typed, render(getattr(decode, typed)(packet))))
    return row


def main():
    packets = load_packets()
    with open(GOLDEN, "w") as out:
        out.write("# Golden master for WU_decodeData, generated by tools/regen_golden.py.\n")
        out.write("# Characterisation of CURRENT behaviour -- not a specification. Do not edit by hand.\n")
        out.write("\t".join(COLUMNS) + "\n")
        for packet in packets:
            out.write("\t".join(decode_row(packet)) + "\n")
    print("wrote %d rows to %s" % (len(packets), GOLDEN))


if __name__ == "__main__":
    main()
